### PR TITLE
Update kernel to 6.12-rc5

### PR DESCRIPTION
**Pull request by kuruczgy**

### CODE REVIEW

**Comment by kuruczgy** [comment]
Compiling now

**Comment by kuruczgy** [comment]
Ah fuck the zlib compilation failure is back with the updated nixpkgs... I would guess that the recent enabling of rust is causing this issue to surface: https://github.com/NixOS/nixpkgs/commit/3bf9c88c1d8200f17c69bddb0b7dc047e6dfc6fe

**Comment by kuruczgy** [comment]
Solved using `DRM_PANIC_SCREEN_QR_CODE = lib.mkForce no;`

**Comment by powpingdone** [comment]
This patch should fix it as well. https://patchwork.freedesktop.org/patch/msgid/20241003230734.653717-1-ojeda@kernel.org

**Comment by kuruczgy** [comment]
Yeah you are right that's the proper solution... pushed an update

**Comment by kuruczgy** [comment]
Well in theory `DRM_PANIC_SCREEN_QR_CODE` should be enabled now, but for me it's not working, on `echo c > /proc/sysrq-trigger` the screen just freezes, I don't get the QR code.

**Comment by kuruczgy** [comment]
Tested, installs & boots

**Pull request merged**
