### PR TITLE
Add basic feature matrix to README

### LINKED ISSUE #21: Add a proper feature matrix to the README
_Originally posted by @alyraffauf in https://github.com/kuruczgy/x1e-nixos-config/discussions/20#discussioncomment-10825832_

Is it possible to come up with a feature matrix not unlike the ones that asahi has? Their SoC support matrix is a little too detailed, but we could devise a practical one (wifi, bluetooth, suspend, speakers, etc).
image
image

### PR DESCRIPTION
**Pull request by alyraffauf**
Closes #21. Needs further discussion, so marking as draft.

Probably needs additional details for the notes column, but this is where I'm at with it. Would love to hear any other details we should add.

### CODE REVIEW

**Comment by kuruczgy** [comment]
Might as well use some of the more colorful unicode characteres for the categories
  - ✅ (https://emojipedia.org/check-mark-button) for fully working
  - 🟨 (https://emojipedia.org/large-yellow-square) for half working, described in note
  - ❌ (https://emojipedia.org/cross-mark) for not working
  - ❔ (https://emojipedia.org/white-question-mark) for never tried but possibly working, described in note

I like the alphabetical sorting, makes sense.

Content:

I think everything USB-C related should be in single block, something like this:
- USB-C booting ✅
- USB-C DisplayPort Alt Mode ❔
- USB-C USB 3/4 ❔
- USB-C PCIe ❌

Others:
- Hardware video decoding ❌
- Microphone ❌
- Camera ❌
- Battery charging + indicator ✅ (I think this is what you meant by "Power Management"? IMO should be a bit more specific)

**Comment by kuruczgy** [comment]
> USB 3/4 should work if booting does, updating now.

Nope, unless you have and USB4 device to test with, and can confirm with extensive testing that it is getting the advertised bandwidth, this should stay a question mark. There is a lot of stuff that goes into full USB4 support (configuring all the internal chip interconnects correctly, regulators, retimers, etc.), and I think not everything is complete yet.

Also I am not even familiar with the full feature set of USB4 (e.g. how is dp and pcie "tunneling" different from alt mode?), so I feel like this should stay a question mark for a while, until we learn more about USB4 and can confirm that every feature is working.

> As for power management, I'm mainly referring to power-profiles-daemon and managing various power modes. I haven't tested this yet, but I'm assuming it doesn't work. Battery charge + indicator can definitely be their own line items though. I'll do some more testing.

Does it do anything other than setting the cpufreq governor?

---

Also FYI about the commits (but I will fix this up before merging anyway if you don't want to bother):
- Please follow the existing commit message style. First word capitalized, imperative mood, no period at the end.
  So something like `Add basic feature matrix to the README` should be the commit msg for this PR. (Yes having scopes like `README:` at the start would make some sense, but it should take an explicit proposal if we want to change the commit message style.)
- There is no reason for this PR to have multiple commits, it should all be squashed into one.

**Comment by alyraffauf** [comment]
> Nope, unless you have and USB4 device to test with, and can confirm with extensive testing that it is getting the advertised bandwidth, this should stay a question mark. There is a lot of stuff that goes into full USB4 support (configuring all the internal chip interconnects correctly, regulators, retimers, etc.), and I think not everything is complete yet.

Oh right, forgot USB4 was distinct from USB3 for a second. 😅 Oopsie. I'll mark it as unknown.

> Does it do anything other than setting the cpufreq governor?

Yes, for x86 processors, AMD and Intel pstate drivers control a whole host of thermal and power limits across the SoC. On Windows Qualcomm chips expose something similar (Best power efficiency, balanced, best performance). I am pretty sure this is related to thermal governors: 
https://docs.qualcomm.com/bundle/publicresource/topics/80-70014-30/get-started-thermal.html
https://docs.qualcomm.com/bundle/publicresource/topics/80-70014-30/thermal%2520architecture.html

Either way, this is not exposed by power-profiles-daemon and other power management daemons (eg. TLP). But it does seem like wayyyy less of a big deal for performance and efficiency for Qualcomm chips, so it's not really that important and can be removed unless we want to specify it is not easily configurable in software.

> Also FYI about the commits (but I will fix this up before merging anyway if you don't want to bother):

No worries, I knew this would take a few revisions, I can squash and fixup the commit naming scheme.

**Comment by kuruczgy** [comment]
@alyraffauf I pushed some minor changes, please take a look if you approve of them.

**Comment by alyraffauf** [comment]
Looks good to me!

**Review by kuruczgy — APPROVED** [review]

**Comment by kuruczgy** [comment]
Merged, thank you!

**Pull request merged**
