### PR TITLE
update kernel to rc6 + comment out unncessary initrd modules

### PR DESCRIPTION
**Pull request by JakoDel**
very basic changes as title says, I just updated the kernel and found along the way two modules that dont apply to our device.
Haven't tested yet however. shame that the in-kernel pd-mapper seems to not be ready yet.

### CODE REVIEW

**Comment by kuruczgy** [comment]
Updated with some additional modifications, removed the (probably) unnecessary patches for the kernel, and removed some further initrd modules. Not tested yet, will try to do tomorrow.

**Comment by JakoDel** [comment]
> Updated with some additional modifications, removed the (probably) unnecessary patches for the kernel, and removed some further initrd modules. Not tested yet, will try to do tomorrow.

I've given it a try as well and I'm getting 

msm_dpu ae01000.display-controller: [drm:adreno_request_fw [msm]]
*ERROR* failed to load gen70500_sqe.fw

followed by the system waiting 1m 30s for /root and then entering emergency mode.

I reinstalled the system without removing the already present boot files in SYSTEM_DRV, but I dont think it has anything to do with this issue

**Comment by JakoDel** [comment]
Nice, so GitHub removes commits in pull requests when they are deleted (I force-synced) from the forked repo they come from. My bad but well, surely not a big loss.

**Comment by kuruczgy** [comment]
Yeah, don't use the main branch, create a separate one for PRs. But don't worry about this one, I will submit the kernel update + module trim of my own soon hopefully.

**Comment by kuruczgy** [comment]
> it's followed by the system waiting 1m 30s for /root and then entering emergency mode because of the missing dependency (the firmware file).

This was because I also accidentally removed the `nvme` module, oops. This should be fixed in #5.

#4 and #5 together should now cover what this PR was.

**Pull request closed without merging**
