### PR TITLE
Add formatter and CI formatting check

### LINKED ISSUE #56: Reformat project using `nixfmt-rfc-style`

### PR DESCRIPTION
**Pull request by eureka-cpu**
Closes #56 

Reformats the project using the RFC style formatter. Specifies the formatter package in the flake. Adds a check to CI on pull request that fails if nix files are not properly formatted.

### CODE REVIEW

**Comment by kuruczgy** [comment]
Cool! Some quick ideas, I am on my phone right now so can't do a proper review yet:
- add a `.git-blame-ignore-revs` file (obviously that has to be done in a second commit)
- maybe add instructions about formatting to the README? I don't think we have a "contributing" section yet but maybe we should...

**Comment by kuruczgy** [comment]
Fuck whyyy. When I `nix fmt` I get this warning:
> Passing directories or non-Nix files (such as ".") is deprecated and will be unsupported soon, please use https://treefmt.com/ instead, e.g. via https://github.com/numtide/treefmt-nix

See: https://github.com/NixOS/nixfmt/issues/151

So we either have to depend on https://github.com/numtide/treefmt-nix (not a fan of adding a flake dependency for such a trivial thing), or roll our own with something like `find -name '*.nix'` or `git ls-files -- '*.nix'`.

**Comment by eureka-cpu** [comment]
To be honest, you would probably be better off using a more stable formatter like alejandra or nixpkgs-fmt. The readme for the rfc formatter indicates it is still extremely unstable software.

**Comment by kuruczgy** [comment]
What about something like this for formatting/checking all files? This should handle both tracked and untracked files, and also respect `.gitignore`:
```bash
git ls-files --cached --others --exclude-standard -z -- '*.nix' | xargs -0 nixfmt
```

Regarding nixfmt, I fear that it's in the "technically experimental but all other reasonable options are already deprecated" territory, same as flakes. They are already reformatting huge swaths of nixpkgs with it, look at this PR from 5 days ago (+706,935 -433,885): https://github.com/NixOS/nixpkgs/pull/322537
If it's good enough for nixpkgs, I don't see why it would not be good enough for us.

**Comment by eureka-cpu** [comment]
> What about something like this for formatting/checking all files? This should handle both tracked and untracked files, and also respect `.gitignore`:
> 
> ```shell
> git ls-files --cached --others --exclude-standard -z -- '*.nix' | xargs -0 nixfmt
> ```
> 
> Regarding nixfmt, I fear that it's in the "technically experimental but all other reasonable options are already deprecated" territory, same as flakes. They are already reformatting huge swaths of nixpkgs with it, look at this PR from 5 days ago (+706,935 -433,885): [NixOS/nixpkgs#322537](https://github.com/NixOS/nixpkgs/pull/322537) If it's good enough for nixpkgs, I don't see why it would not be good enough for us.

I suppose something like that would work just fine. For now it seems this is only a warning, so maybe it's not worth worrying over?

**Comment by kuruczgy** [comment]
Also `.git-blame-ignore-revs` might be problematic, because it will also ignore relevant changes from the reformat commit like the ci.yml or the `formatter` definition... maybe we should split it into two commits, the first just adds the formatter and CI but does not change anything else, and then the next one is just a pure reformat commit.

**Comment by infinisil** [comment]
Hey, (a) nixfmt maintainer here! We very intentionally deprecated that recursive mode, because the details get tricky, but it's all behavior generic for all formatters, making it perfect for treefmt. This includes:
- Specifying the files to format, in particular also avoiding "files" like `.git/logs/refs/remotes/foo/bar.nix`.
- Formatting files efficiently in parallel.
- Avoiding formatting of files that don't need it (using a cache).

If you want to see treefmt-nix in practice, you can check out the config in nixfmt itself. The definition of `nixfmtEval` is [here](https://github.com/NixOS/nixfmt/blob/master/default.nix#L65-L77), then you can build `treefmtEval.config.build.check source` to get something that fails in CI with a [good error](https://github.com/NixOS/nixfmt/actions/runs/11958753808/job/33338970091) and add `treefmtEval.config.build.wrapper` to the development shell to get a locally runnable `treefmt` command.

Anyways, totally up to you how you want to handle it, but feel free to let us know of any problems or suggestions for improvement in the nixfmt issue tracker :)

Oh and you can consider nixfmt stable, we plan to make the 1.0 release very soon, the formatting should only change in minor ways going forward.

**Comment by kuruczgy** [comment]
@infinisil wow, definitely did not expect you to comment here, thank you for chiming in :) It's good to hear that nixfmt will be "officially" stabilized soon.

Yeah, fine, I did check out treefmt and treefmt-nix since you are recommending it. I read through some of the code in both, my only nitpick is that [the flake example in the treefmt-nix readme](https://github.com/numtide/treefmt-nix/tree/main?tab=readme-ov-file#flakes) is broken. (`treefmtEval` is an attrset of systems but the code is trying to refer to its `config` attribute.) Other than this both projects seem reasonable, I did not find anything objectionable.

(`xargs` does apparently have a parallel option, so my one-liner would only be missing caching from the features you listed if I used that.) But I do get the value proposition of treefmt and treefmt-nix now, and in fact they seem like something I might want to use in future projects with more complex formatting requirements using multiple formatters.

And at that point I might as well start using it here already. Getting some experience with it and learning any of its quirks on a simpler project is probably more valuable than avoiding the extra dependency in favor of the one-liner that technically would also work in this particular scenario.

I updated the PR to use treefmt-nix.

**Review by eureka-cpu — COMMENTED** [review]
LGTM thanks for the refactors @kuruczgy

**Pull request merged**
